name: Daily Check-in

on:
  schedule:
    - cron: '0 18 * * *'  # 北京时间每天 2:00（UTC+8）

  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    permissions:
      contents: read     # 必须启用，否则无法检出代码
      actions: write     # 可选，用于写入日志
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          SITE_TOKEN: ${{ secrets.SITE_TOKEN }}  # 将 Secret 注入环境变量
          SERVER_JANG_SCKEY: ${{ secrets.SERVER_JANG_SCKEY }}
        run: |
          python index.py