name: Daily Check-in

on:
  schedule:
    - cron: '0 18 * * *'  # 北京时间每天 2:00（UTC+8）

jobs:
  checkin:
    runs-on: ubuntu-latest
    permissions:
      contents: read     # 必须启用，否则无法检出代码
      actions: write     # 可选，用于写入日志
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        id: cache-pip-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-requests
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requests
        if: steps.cache-pip-dependencies.outputs.cache-hit != 'true'
        run: pip install requests

      - name: Run script
        env:
          SITE_TOKEN: ${{ secrets.SITE_TOKEN }}  # 将 Secret 注入环境变量
        run: |
          python index.py

  