name: Signladder Auto Check-in

on:
  schedule:
    - cron: '30 23 * * *'  # 每天 UTC 23:30（东八区 7:30）
  workflow_dispatch:

jobs:
  signladder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Run signladder script
      env:
        COOKIE_LADDER_STR: ${{ secrets.COOKIE_LADDER_STR }}
        SERVER_JANG_SCKEY: ${{ secrets.SERVER_JANG_SCKEY }}
      run: python signladder.py
